# Generated by Django 4.2.24 on 2026-03-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0004_remove_voluntario_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voluntario',
            name='area',
            field=models.CharField(choices=[('Evento de adoção', 'Evento de Adoção'), ('Cuidados e Bem-Estar', 'Cuidados e Bem-Estar'), ('Associado', 'Associado'), ('Outras tarefas', 'Outras Tarefas')], max_length=100),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='cidade',
            field=models.CharField(choices=[('São José dos Campos', 'São José dos Campos'), ('Jacareí', 'Jacareí'), ('Caçapava', 'Caçapava'), ('Taubaté', 'Taubaté')], max_length=50),
        ),
    ]
