# Generated by Django 4.2.24 on 2026-03-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animais/fotos/')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('ADOTADO', 'Adotado')], default='DISPONIVEL', max_length=20)),
                ('data_chegada', models.DateField(blank=True, null=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
