# Generated by Django 4.2.24 on 2026-03-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível para Adoção'), ('ADOTADO', 'Adotado'), ('TRATAMENTO', 'Em Tratamento')], default='DISPONIVEL', max_length=20),
        ),
    ]
